//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.04 at 03:24:36 PM CET 
//


package se.qbranch.tickets;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.qbranch.tickets package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.qbranch.tickets
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ticket }
     * 
     */
    public Ticket createTicket() {
        return new Ticket();
    }

    /**
     * Create an instance of {@link CreateNewTicket }
     * 
     */
    public CreateNewTicket createCreateNewTicket() {
        return new CreateNewTicket();
    }

    /**
     * Create an instance of {@link UpdateTicketStatus }
     * 
     */
    public UpdateTicketStatus createUpdateTicketStatus() {
        return new UpdateTicketStatus();
    }

    /**
     * Create an instance of {@link AddNoteToTicket }
     * 
     */
    public AddNoteToTicket createAddNoteToTicket() {
        return new AddNoteToTicket();
    }

    /**
     * Create an instance of {@link CreateNewTicket.Notes }
     * 
     */
    public CreateNewTicket.Notes createCreateNewTicketNotes() {
        return new CreateNewTicket.Notes();
    }

    /**
     * Create an instance of {@link Ticket.Attachments }
     * 
     */
    public Ticket.Attachments createTicketAttachments() {
        return new Ticket.Attachments();
    }

    /**
     * Create an instance of {@link Ticket.Notes }
     * 
     */
    public Ticket.Notes createTicketNotes() {
        return new Ticket.Notes();
    }

    /**
     * Create an instance of {@link Ticket.Contact }
     * 
     */
    public Ticket.Contact createTicketContact() {
        return new Ticket.Contact();
    }

    /**
     * Create an instance of {@link Ticket.Info }
     * 
     */
    public Ticket.Info createTicketInfo() {
        return new Ticket.Info();
    }

    /**
     * Create an instance of {@link Ticket.Business }
     * 
     */
    public Ticket.Business createTicketBusiness() {
        return new Ticket.Business();
    }

    /**
     * Create an instance of {@link Ticket.Classification }
     * 
     */
    public Ticket.Classification createTicketClassification() {
        return new Ticket.Classification();
    }

    /**
     * Create an instance of {@link CreateNewTicket.Contact }
     * 
     */
    public CreateNewTicket.Contact createCreateNewTicketContact() {
        return new CreateNewTicket.Contact();
    }

    /**
     * Create an instance of {@link CreateNewTicket.Info }
     * 
     */
    public CreateNewTicket.Info createCreateNewTicketInfo() {
        return new CreateNewTicket.Info();
    }

    /**
     * Create an instance of {@link CreateNewTicket.Business }
     * 
     */
    public CreateNewTicket.Business createCreateNewTicketBusiness() {
        return new CreateNewTicket.Business();
    }

    /**
     * Create an instance of {@link UpdateTicketStatus.Note }
     * 
     */
    public UpdateTicketStatus.Note createUpdateTicketStatusNote() {
        return new UpdateTicketStatus.Note();
    }

    /**
     * Create an instance of {@link AddNoteToTicket.Note }
     * 
     */
    public AddNoteToTicket.Note createAddNoteToTicketNote() {
        return new AddNoteToTicket.Note();
    }

    /**
     * Create an instance of {@link CreateNewTicket.Notes.Note }
     * 
     */
    public CreateNewTicket.Notes.Note createCreateNewTicketNotesNote() {
        return new CreateNewTicket.Notes.Note();
    }

    /**
     * Create an instance of {@link Ticket.Attachments.Attachment }
     * 
     */
    public Ticket.Attachments.Attachment createTicketAttachmentsAttachment() {
        return new Ticket.Attachments.Attachment();
    }

    /**
     * Create an instance of {@link Ticket.Notes.Note }
     * 
     */
    public Ticket.Notes.Note createTicketNotesNote() {
        return new Ticket.Notes.Note();
    }

}
