//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://schemas.qbranch.se/2014/04/ticket", ClrNamespace="schemas.qbranch.se._2014._04.ticket")]

namespace schemas.qbranch.se._2014._04.ticket
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ticket", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
    public partial class ticket : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int customer_idField;
        
        private string ticket_idField;
        
        private string ticket_guidField;
        
        private string ticket_descriptionField;
        
        private string ticket_statusField;
        
        private string service_idField;
        
        private string service_nameField;
        
        private string application_idField;
        
        private string application_nameField;
        
        private string ticket_typeField;
        
        private schemas.qbranch.se._2014._04.ticket.ticket.contactType contactField;
        
        private schemas.qbranch.se._2014._04.ticket.ticket.infoType infoField;
        
        private schemas.qbranch.se._2014._04.ticket.ticket.notesType notesField;
        
        private schemas.qbranch.se._2014._04.ticket.ticket.businessType businessField;
        
        private schemas.qbranch.se._2014._04.ticket.ticket.classificationType classificationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int customer_id
        {
            get
            {
                return this.customer_idField;
            }
            set
            {
                this.customer_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ticket_id
        {
            get
            {
                return this.ticket_idField;
            }
            set
            {
                this.ticket_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string ticket_guid
        {
            get
            {
                return this.ticket_guidField;
            }
            set
            {
                this.ticket_guidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string ticket_description
        {
            get
            {
                return this.ticket_descriptionField;
            }
            set
            {
                this.ticket_descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string ticket_status
        {
            get
            {
                return this.ticket_statusField;
            }
            set
            {
                this.ticket_statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string service_id
        {
            get
            {
                return this.service_idField;
            }
            set
            {
                this.service_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string service_name
        {
            get
            {
                return this.service_nameField;
            }
            set
            {
                this.service_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string application_id
        {
            get
            {
                return this.application_idField;
            }
            set
            {
                this.application_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string application_name
        {
            get
            {
                return this.application_nameField;
            }
            set
            {
                this.application_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=9)]
        public string ticket_type
        {
            get
            {
                return this.ticket_typeField;
            }
            set
            {
                this.ticket_typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public schemas.qbranch.se._2014._04.ticket.ticket.contactType contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public schemas.qbranch.se._2014._04.ticket.ticket.infoType info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public schemas.qbranch.se._2014._04.ticket.ticket.notesType notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public schemas.qbranch.se._2014._04.ticket.ticket.businessType business
        {
            get
            {
                return this.businessField;
            }
            set
            {
                this.businessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=14)]
        public schemas.qbranch.se._2014._04.ticket.ticket.classificationType classification
        {
            get
            {
                return this.classificationField;
            }
            set
            {
                this.classificationField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ticket.contactType", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
        public partial class contactType : object, System.Runtime.Serialization.IExtensibleDataObject
        {
            
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string emailField;
            
            private string nameField;
            
            private string first_nameField;
            
            private string last_nameField;
            
            private string languageField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string email
            {
                get
                {
                    return this.emailField;
                }
                set
                {
                    this.emailField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string name
            {
                get
                {
                    return this.nameField;
                }
                set
                {
                    this.nameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
            public string first_name
            {
                get
                {
                    return this.first_nameField;
                }
                set
                {
                    this.first_nameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
            public string last_name
            {
                get
                {
                    return this.last_nameField;
                }
                set
                {
                    this.last_nameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
            public string language
            {
                get
                {
                    return this.languageField;
                }
                set
                {
                    this.languageField = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ticket.infoType", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
        public partial class infoType : object, System.Runtime.Serialization.IExtensibleDataObject
        {
            
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private System.DateTime created_dateField;
            
            private System.Nullable<System.DateTime> modified_dateField;
            
            private System.Nullable<System.DateTime> solved_dateField;
            
            private System.Nullable<System.DateTime> closed_dateField;
            
            private System.Nullable<System.DateTime> estimated_start_dateField;
            
            private System.Nullable<System.DateTime> estimated_complete_dateField;
            
            private System.Nullable<int> estimated_time_in_secondsField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public System.DateTime created_date
            {
                get
                {
                    return this.created_dateField;
                }
                set
                {
                    this.created_dateField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public System.Nullable<System.DateTime> modified_date
            {
                get
                {
                    return this.modified_dateField;
                }
                set
                {
                    this.modified_dateField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public System.Nullable<System.DateTime> solved_date
            {
                get
                {
                    return this.solved_dateField;
                }
                set
                {
                    this.solved_dateField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
            public System.Nullable<System.DateTime> closed_date
            {
                get
                {
                    return this.closed_dateField;
                }
                set
                {
                    this.closed_dateField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
            public System.Nullable<System.DateTime> estimated_start_date
            {
                get
                {
                    return this.estimated_start_dateField;
                }
                set
                {
                    this.estimated_start_dateField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
            public System.Nullable<System.DateTime> estimated_complete_date
            {
                get
                {
                    return this.estimated_complete_dateField;
                }
                set
                {
                    this.estimated_complete_dateField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
            public System.Nullable<int> estimated_time_in_seconds
            {
                get
                {
                    return this.estimated_time_in_secondsField;
                }
                set
                {
                    this.estimated_time_in_secondsField = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ticket.businessType", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
        public partial class businessType : object, System.Runtime.Serialization.IExtensibleDataObject
        {
            
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string impactField;
            
            private string impact_descriptionField;
            
            private string priorityField;
            
            private string priority_descriptionField;
            
            private string severityField;
            
            private string severity_descriptionField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public string impact
            {
                get
                {
                    return this.impactField;
                }
                set
                {
                    this.impactField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public string impact_description
            {
                get
                {
                    return this.impact_descriptionField;
                }
                set
                {
                    this.impact_descriptionField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public string priority
            {
                get
                {
                    return this.priorityField;
                }
                set
                {
                    this.priorityField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public string priority_description
            {
                get
                {
                    return this.priority_descriptionField;
                }
                set
                {
                    this.priority_descriptionField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public string severity
            {
                get
                {
                    return this.severityField;
                }
                set
                {
                    this.severityField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public string severity_description
            {
                get
                {
                    return this.severity_descriptionField;
                }
                set
                {
                    this.severity_descriptionField = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ticket.classificationType", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
        public partial class classificationType : object, System.Runtime.Serialization.IExtensibleDataObject
        {
            
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string idField;
            
            private string categoryField;
            
            private string nameField;
            
            private string descriptionField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
            public string category
            {
                get
                {
                    return this.categoryField;
                }
                set
                {
                    this.categoryField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
            public string name
            {
                get
                {
                    return this.nameField;
                }
                set
                {
                    this.nameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
            public string description
            {
                get
                {
                    return this.descriptionField;
                }
                set
                {
                    this.descriptionField = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ticket.notesType", Namespace="http://schemas.qbranch.se/2014/04/ticket", ItemName="note")]
        public class notesType : System.Collections.Generic.List<schemas.qbranch.se._2014._04.ticket.note>
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="note", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
    public partial class note : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string textField;
        
        private string typeField;
        
        private System.DateTime dateField;
        
        private string user_emailField;
        
        private string user_nameField;
        
        private string user_first_nameField;
        
        private string user_last_nameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string user_email
        {
            get
            {
                return this.user_emailField;
            }
            set
            {
                this.user_emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string user_name
        {
            get
            {
                return this.user_nameField;
            }
            set
            {
                this.user_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string user_first_name
        {
            get
            {
                return this.user_first_nameField;
            }
            set
            {
                this.user_first_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string user_last_name
        {
            get
            {
                return this.user_last_nameField;
            }
            set
            {
                this.user_last_nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="create_new_ticket", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
    public partial class create_new_ticket : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int customer_idField;
        
        private string ticket_guidField;
        
        private string ticket_descriptionField;
        
        private string service_idField;
        
        private string classification_idField;
        
        private string application_idField;
        
        private string ticket_typeField;
        
        private string ticket_statusField;
        
        private schemas.qbranch.se._2014._04.ticket.create_new_ticket.contactType contactField;
        
        private schemas.qbranch.se._2014._04.ticket.create_new_ticket.infoType infoField;
        
        private schemas.qbranch.se._2014._04.ticket.create_new_ticket.notesType notesField;
        
        private schemas.qbranch.se._2014._04.ticket.create_new_ticket.businessType businessField;
        
        private schemas.qbranch.se._2014._04.ticket.create_new_ticket.classificationType classificationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int customer_id
        {
            get
            {
                return this.customer_idField;
            }
            set
            {
                this.customer_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ticket_guid
        {
            get
            {
                return this.ticket_guidField;
            }
            set
            {
                this.ticket_guidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string ticket_description
        {
            get
            {
                return this.ticket_descriptionField;
            }
            set
            {
                this.ticket_descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string service_id
        {
            get
            {
                return this.service_idField;
            }
            set
            {
                this.service_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string classification_id
        {
            get
            {
                return this.classification_idField;
            }
            set
            {
                this.classification_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string application_id
        {
            get
            {
                return this.application_idField;
            }
            set
            {
                this.application_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string ticket_type
        {
            get
            {
                return this.ticket_typeField;
            }
            set
            {
                this.ticket_typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string ticket_status
        {
            get
            {
                return this.ticket_statusField;
            }
            set
            {
                this.ticket_statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public schemas.qbranch.se._2014._04.ticket.create_new_ticket.contactType contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public schemas.qbranch.se._2014._04.ticket.create_new_ticket.infoType info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public schemas.qbranch.se._2014._04.ticket.create_new_ticket.notesType notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public schemas.qbranch.se._2014._04.ticket.create_new_ticket.businessType business
        {
            get
            {
                return this.businessField;
            }
            set
            {
                this.businessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=12)]
        public schemas.qbranch.se._2014._04.ticket.create_new_ticket.classificationType classification
        {
            get
            {
                return this.classificationField;
            }
            set
            {
                this.classificationField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="create_new_ticket.contactType", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
        public partial class contactType : object, System.Runtime.Serialization.IExtensibleDataObject
        {
            
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string emailField;
            
            private string nameField;
            
            private string first_nameField;
            
            private string last_nameField;
            
            private string languageField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string email
            {
                get
                {
                    return this.emailField;
                }
                set
                {
                    this.emailField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string name
            {
                get
                {
                    return this.nameField;
                }
                set
                {
                    this.nameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
            public string first_name
            {
                get
                {
                    return this.first_nameField;
                }
                set
                {
                    this.first_nameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
            public string last_name
            {
                get
                {
                    return this.last_nameField;
                }
                set
                {
                    this.last_nameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
            public string language
            {
                get
                {
                    return this.languageField;
                }
                set
                {
                    this.languageField = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="create_new_ticket.infoType", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
        public partial class infoType : object, System.Runtime.Serialization.IExtensibleDataObject
        {
            
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private System.DateTime created_dateField;
            
            private System.Nullable<System.DateTime> modified_dateField;
            
            private System.Nullable<System.DateTime> solved_dateField;
            
            private System.Nullable<System.DateTime> closed_dateField;
            
            private System.Nullable<System.DateTime> estimated_start_dateField;
            
            private System.Nullable<System.DateTime> estimated_complete_dateField;
            
            private System.Nullable<int> estimated_time_in_secondsField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public System.DateTime created_date
            {
                get
                {
                    return this.created_dateField;
                }
                set
                {
                    this.created_dateField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public System.Nullable<System.DateTime> modified_date
            {
                get
                {
                    return this.modified_dateField;
                }
                set
                {
                    this.modified_dateField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public System.Nullable<System.DateTime> solved_date
            {
                get
                {
                    return this.solved_dateField;
                }
                set
                {
                    this.solved_dateField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
            public System.Nullable<System.DateTime> closed_date
            {
                get
                {
                    return this.closed_dateField;
                }
                set
                {
                    this.closed_dateField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
            public System.Nullable<System.DateTime> estimated_start_date
            {
                get
                {
                    return this.estimated_start_dateField;
                }
                set
                {
                    this.estimated_start_dateField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
            public System.Nullable<System.DateTime> estimated_complete_date
            {
                get
                {
                    return this.estimated_complete_dateField;
                }
                set
                {
                    this.estimated_complete_dateField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
            public System.Nullable<int> estimated_time_in_seconds
            {
                get
                {
                    return this.estimated_time_in_secondsField;
                }
                set
                {
                    this.estimated_time_in_secondsField = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="create_new_ticket.businessType", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
        public partial class businessType : object, System.Runtime.Serialization.IExtensibleDataObject
        {
            
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string impactField;
            
            private string priorityField;
            
            private string severityField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public string impact
            {
                get
                {
                    return this.impactField;
                }
                set
                {
                    this.impactField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public string priority
            {
                get
                {
                    return this.priorityField;
                }
                set
                {
                    this.priorityField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public string severity
            {
                get
                {
                    return this.severityField;
                }
                set
                {
                    this.severityField = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="create_new_ticket.classificationType", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
        public partial class classificationType : object, System.Runtime.Serialization.IExtensibleDataObject
        {
            
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string idField;
            
            private string categoryField;
            
            private string nameField;
            
            private string descriptionField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
            public string category
            {
                get
                {
                    return this.categoryField;
                }
                set
                {
                    this.categoryField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
            public string name
            {
                get
                {
                    return this.nameField;
                }
                set
                {
                    this.nameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
            public string description
            {
                get
                {
                    return this.descriptionField;
                }
                set
                {
                    this.descriptionField = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="create_new_ticket.notesType", Namespace="http://schemas.qbranch.se/2014/04/ticket", ItemName="note")]
        public class notesType : System.Collections.Generic.List<schemas.qbranch.se._2014._04.ticket.create_new_ticket.notesType.noteType>
        {
            
            [System.Diagnostics.DebuggerStepThroughAttribute()]
            [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
            [System.Runtime.Serialization.DataContractAttribute(Name="create_new_ticket.notesType.noteType", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
            public partial class noteType : object, System.Runtime.Serialization.IExtensibleDataObject
            {
                
                private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
                
                private string textField;
                
                private string typeField;
                
                private System.DateTime dateField;
                
                private string user_emailField;
                
                private string user_nameField;
                
                private string user_first_nameField;
                
                private string user_last_nameField;
                
                public System.Runtime.Serialization.ExtensionDataObject ExtensionData
                {
                    get
                    {
                        return this.extensionDataField;
                    }
                    set
                    {
                        this.extensionDataField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
                public string text
                {
                    get
                    {
                        return this.textField;
                    }
                    set
                    {
                        this.textField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
                public string type
                {
                    get
                    {
                        return this.typeField;
                    }
                    set
                    {
                        this.typeField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
                public System.DateTime date
                {
                    get
                    {
                        return this.dateField;
                    }
                    set
                    {
                        this.dateField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
                public string user_email
                {
                    get
                    {
                        return this.user_emailField;
                    }
                    set
                    {
                        this.user_emailField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
                public string user_name
                {
                    get
                    {
                        return this.user_nameField;
                    }
                    set
                    {
                        this.user_nameField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
                public string user_first_name
                {
                    get
                    {
                        return this.user_first_nameField;
                    }
                    set
                    {
                        this.user_first_nameField = value;
                    }
                }
                
                [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
                public string user_last_name
                {
                    get
                    {
                        return this.user_last_nameField;
                    }
                    set
                    {
                        this.user_last_nameField = value;
                    }
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="add_note_to_ticket", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
    public partial class add_note_to_ticket : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int customer_idField;
        
        private string ticket_idField;
        
        private schemas.qbranch.se._2014._04.ticket.add_note_to_ticket.noteType noteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int customer_id
        {
            get
            {
                return this.customer_idField;
            }
            set
            {
                this.customer_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ticket_id
        {
            get
            {
                return this.ticket_idField;
            }
            set
            {
                this.ticket_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public schemas.qbranch.se._2014._04.ticket.add_note_to_ticket.noteType note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="add_note_to_ticket.noteType", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
        public partial class noteType : object, System.Runtime.Serialization.IExtensibleDataObject
        {
            
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string textField;
            
            private string user_emailField;
            
            private string user_nameField;
            
            private string user_first_nameField;
            
            private string user_last_nameField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string text
            {
                get
                {
                    return this.textField;
                }
                set
                {
                    this.textField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string user_email
            {
                get
                {
                    return this.user_emailField;
                }
                set
                {
                    this.user_emailField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string user_name
            {
                get
                {
                    return this.user_nameField;
                }
                set
                {
                    this.user_nameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
            public string user_first_name
            {
                get
                {
                    return this.user_first_nameField;
                }
                set
                {
                    this.user_first_nameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
            public string user_last_name
            {
                get
                {
                    return this.user_last_nameField;
                }
                set
                {
                    this.user_last_nameField = value;
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="update_ticket_status", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
    public partial class update_ticket_status : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int customer_idField;
        
        private string ticket_idField;
        
        private string ticket_statusField;
        
        private schemas.qbranch.se._2014._04.ticket.update_ticket_status.noteType noteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int customer_id
        {
            get
            {
                return this.customer_idField;
            }
            set
            {
                this.customer_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ticket_id
        {
            get
            {
                return this.ticket_idField;
            }
            set
            {
                this.ticket_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ticket_status
        {
            get
            {
                return this.ticket_statusField;
            }
            set
            {
                this.ticket_statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public schemas.qbranch.se._2014._04.ticket.update_ticket_status.noteType note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="update_ticket_status.noteType", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
        public partial class noteType : object, System.Runtime.Serialization.IExtensibleDataObject
        {
            
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private string textField;
            
            private string user_emailField;
            
            private string user_nameField;
            
            private string user_first_nameField;
            
            private string user_last_nameField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData
            {
                get
                {
                    return this.extensionDataField;
                }
                set
                {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string text
            {
                get
                {
                    return this.textField;
                }
                set
                {
                    this.textField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string user_email
            {
                get
                {
                    return this.user_emailField;
                }
                set
                {
                    this.user_emailField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string user_name
            {
                get
                {
                    return this.user_nameField;
                }
                set
                {
                    this.user_nameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
            public string user_first_name
            {
                get
                {
                    return this.user_first_nameField;
                }
                set
                {
                    this.user_first_nameField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
            public string user_last_name
            {
                get
                {
                    return this.user_last_nameField;
                }
                set
                {
                    this.user_last_nameField = value;
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="add_attachment_to_ticket", Namespace="http://schemas.qbranch.se/2014/04/ticket")]
    public partial class add_attachment_to_ticket : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string customer_idField;
        
        private string ticket_idField;
        
        private string attachment_nameField;
        
        private string attachment_uriField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string customer_id
        {
            get
            {
                return this.customer_idField;
            }
            set
            {
                this.customer_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ticket_id
        {
            get
            {
                return this.ticket_idField;
            }
            set
            {
                this.ticket_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string attachment_name
        {
            get
            {
                return this.attachment_nameField;
            }
            set
            {
                this.attachment_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string attachment_uri
        {
            get
            {
                return this.attachment_uriField;
            }
            set
            {
                this.attachment_uriField = value;
            }
        }
    }
}
