//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket", IsNullable=false)]
public partial class ticket {
    
    private int customer_idField;
    
    private string ticket_idField;
    
    private string ticket_descriptionField;
    
    private string ticket_statusField;
    
    private string service_idField;
    
    private string service_nameField;
    
    private string classification_idField;
    
    private string classification_nameField;
    
    private type typeField;
    
    private contact contactField;
    
    private info infoField;
    
    private note[] notesField;
    
    private business businessField;
    
    private attachment[] attachmentsField;
    
    /// <remarks/>
    public int customer_id {
        get {
            return this.customer_idField;
        }
        set {
            this.customer_idField = value;
        }
    }
    
    /// <remarks/>
    public string ticket_id {
        get {
            return this.ticket_idField;
        }
        set {
            this.ticket_idField = value;
        }
    }
    
    /// <remarks/>
    public string ticket_description {
        get {
            return this.ticket_descriptionField;
        }
        set {
            this.ticket_descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string ticket_status {
        get {
            return this.ticket_statusField;
        }
        set {
            this.ticket_statusField = value;
        }
    }
    
    /// <remarks/>
    public string service_id {
        get {
            return this.service_idField;
        }
        set {
            this.service_idField = value;
        }
    }
    
    /// <remarks/>
    public string service_name {
        get {
            return this.service_nameField;
        }
        set {
            this.service_nameField = value;
        }
    }
    
    /// <remarks/>
    public string classification_id {
        get {
            return this.classification_idField;
        }
        set {
            this.classification_idField = value;
        }
    }
    
    /// <remarks/>
    public string classification_name {
        get {
            return this.classification_nameField;
        }
        set {
            this.classification_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    public type type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    public contact contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    public info info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    [System.Xml.Serialization.XmlArrayItemAttribute("note", IsNullable=false)]
    public note[] notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    public business business {
        get {
            return this.businessField;
        }
        set {
            this.businessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    [System.Xml.Serialization.XmlArrayItemAttribute("attachment", IsNullable=false)]
    public attachment[] attachments {
        get {
            return this.attachmentsField;
        }
        set {
            this.attachmentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types", IsNullable=false)]
public partial class type {
    
    private typeID idField;
    
    private string descriptionField;
    
    /// <remarks/>
    public typeID id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
public enum typeID {
    
    /// <remarks/>
    chg,
    
    /// <remarks/>
    inc,
    
    /// <remarks/>
    req,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types", IsNullable=false)]
public partial class contact {
    
    private string emailField;
    
    private string first_nameField;
    
    private string last_nameField;
    
    private string languageField;
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string first_name {
        get {
            return this.first_nameField;
        }
        set {
            this.first_nameField = value;
        }
    }
    
    /// <remarks/>
    public string last_name {
        get {
            return this.last_nameField;
        }
        set {
            this.last_nameField = value;
        }
    }
    
    /// <remarks/>
    public string language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types", IsNullable=false)]
public partial class info {
    
    private System.DateTime created_dateField;
    
    private System.DateTime modified_dateField;
    
    private bool modified_dateFieldSpecified;
    
    private System.DateTime solved_dateField;
    
    private bool solved_dateFieldSpecified;
    
    private System.DateTime estimated_start_dateField;
    
    private bool estimated_start_dateFieldSpecified;
    
    private System.DateTime estimated_complete_dateField;
    
    private bool estimated_complete_dateFieldSpecified;
    
    private int estimated_time_in_secondsField;
    
    private bool estimated_time_in_secondsFieldSpecified;
    
    /// <remarks/>
    public System.DateTime created_date {
        get {
            return this.created_dateField;
        }
        set {
            this.created_dateField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime modified_date {
        get {
            return this.modified_dateField;
        }
        set {
            this.modified_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool modified_dateSpecified {
        get {
            return this.modified_dateFieldSpecified;
        }
        set {
            this.modified_dateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime solved_date {
        get {
            return this.solved_dateField;
        }
        set {
            this.solved_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool solved_dateSpecified {
        get {
            return this.solved_dateFieldSpecified;
        }
        set {
            this.solved_dateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime estimated_start_date {
        get {
            return this.estimated_start_dateField;
        }
        set {
            this.estimated_start_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool estimated_start_dateSpecified {
        get {
            return this.estimated_start_dateFieldSpecified;
        }
        set {
            this.estimated_start_dateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime estimated_complete_date {
        get {
            return this.estimated_complete_dateField;
        }
        set {
            this.estimated_complete_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool estimated_complete_dateSpecified {
        get {
            return this.estimated_complete_dateFieldSpecified;
        }
        set {
            this.estimated_complete_dateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int estimated_time_in_seconds {
        get {
            return this.estimated_time_in_secondsField;
        }
        set {
            this.estimated_time_in_secondsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool estimated_time_in_secondsSpecified {
        get {
            return this.estimated_time_in_secondsFieldSpecified;
        }
        set {
            this.estimated_time_in_secondsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types", IsNullable=false)]
public partial class note {
    
    private string textField;
    
    private noteType typeField;
    
    private System.DateTime dateField;
    
    private string user_emailField;
    
    private string user_first_nameField;
    
    private string user_last_nameField;
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public noteType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public string user_email {
        get {
            return this.user_emailField;
        }
        set {
            this.user_emailField = value;
        }
    }
    
    /// <remarks/>
    public string user_first_name {
        get {
            return this.user_first_nameField;
        }
        set {
            this.user_first_nameField = value;
        }
    }
    
    /// <remarks/>
    public string user_last_name {
        get {
            return this.user_last_nameField;
        }
        set {
            this.user_last_nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
public enum noteType {
    
    /// <remarks/>
    history,
    
    /// <remarks/>
    solution,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types", IsNullable=false)]
public partial class business {
    
    private string impactField;
    
    private string impact_descriptionField;
    
    private string priorityField;
    
    private string priority_descriptionField;
    
    private string severityField;
    
    private string severity_descriptionField;
    
    /// <remarks/>
    public string impact {
        get {
            return this.impactField;
        }
        set {
            this.impactField = value;
        }
    }
    
    /// <remarks/>
    public string impact_description {
        get {
            return this.impact_descriptionField;
        }
        set {
            this.impact_descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    public string priority_description {
        get {
            return this.priority_descriptionField;
        }
        set {
            this.priority_descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string severity {
        get {
            return this.severityField;
        }
        set {
            this.severityField = value;
        }
    }
    
    /// <remarks/>
    public string severity_description {
        get {
            return this.severity_descriptionField;
        }
        set {
            this.severity_descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types", IsNullable=false)]
public partial class attachment {
    
    private string nameField;
    
    private string urlField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket", IsNullable=false)]
public partial class create_new_ticket {
    
    private int customer_idField;
    
    private string ticket_descriptionField;
    
    private string service_idField;
    
    private string classification_idField;
    
    private type typeField;
    
    private contact contactField;
    
    private info infoField;
    
    private note[] notesField;
    
    private business businessField;
    
    private attachment[] attachmentsField;
    
    /// <remarks/>
    public int customer_id {
        get {
            return this.customer_idField;
        }
        set {
            this.customer_idField = value;
        }
    }
    
    /// <remarks/>
    public string ticket_description {
        get {
            return this.ticket_descriptionField;
        }
        set {
            this.ticket_descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string service_id {
        get {
            return this.service_idField;
        }
        set {
            this.service_idField = value;
        }
    }
    
    /// <remarks/>
    public string classification_id {
        get {
            return this.classification_idField;
        }
        set {
            this.classification_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    public type type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    public contact contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    public info info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    [System.Xml.Serialization.XmlArrayItemAttribute("note", IsNullable=false)]
    public note[] notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    public business business {
        get {
            return this.businessField;
        }
        set {
            this.businessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    [System.Xml.Serialization.XmlArrayItemAttribute("attachment", IsNullable=false)]
    public attachment[] attachments {
        get {
            return this.attachmentsField;
        }
        set {
            this.attachmentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket", IsNullable=false)]
public partial class add_note_to_ticket {
    
    private int customer_idField;
    
    private string ticket_idField;
    
    private note noteField;
    
    /// <remarks/>
    public int customer_id {
        get {
            return this.customer_idField;
        }
        set {
            this.customer_idField = value;
        }
    }
    
    /// <remarks/>
    public string ticket_id {
        get {
            return this.ticket_idField;
        }
        set {
            this.ticket_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    public note note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket", IsNullable=false)]
public partial class update_ticket_status {
    
    private int customer_idField;
    
    private string ticket_idField;
    
    private update_ticket_statusTicket_status ticket_statusField;
    
    private note noteField;
    
    /// <remarks/>
    public int customer_id {
        get {
            return this.customer_idField;
        }
        set {
            this.customer_idField = value;
        }
    }
    
    /// <remarks/>
    public string ticket_id {
        get {
            return this.ticket_idField;
        }
        set {
            this.ticket_idField = value;
        }
    }
    
    /// <remarks/>
    public update_ticket_statusTicket_status ticket_status {
        get {
            return this.ticket_statusField;
        }
        set {
            this.ticket_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
    public note note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket")]
public enum update_ticket_statusTicket_status {
    
    /// <remarks/>
    closed,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types", IsNullable=false)]
public partial class notes {
    
    private note[] noteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("note")]
    public note[] note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.qbranch.se/2014/04/ticket/types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.qbranch.se/2014/04/ticket/types", IsNullable=false)]
public partial class attachments {
    
    private attachment[] attachmentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attachment")]
    public attachment[] attachment {
        get {
            return this.attachmentField;
        }
        set {
            this.attachmentField = value;
        }
    }
}
